//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Equipment : Item {
		int durability;
		Skill effect;

		public Equipment () {
		}

		public Equipment (int d, Skill e) {
			durability = d;
			effect = e;
		}

		public int getDurability(){
			return durability;
		}

		public void takeDurability (int d) {
			durability -= d;
		}

		public void breakEquipment() {
			//destroy this instance of equipment
		}

		public Skill getEffect() {
			return effect;
		}

	}
}

