//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;

namespace AssemblyCSharp
{
	public class Lockbox : Item {
		ArrayList contents = new ArrayList();

		public Lockbox () {

		}

		public ArrayList getContents() {
			return contents;
		}

		public void setContents(ArrayList c) {
			//for each item in the array, add it to the contents.
			foreach(Item item in c){
				contents.Add(item);
			}
		}

	}
}

