//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Health : Stat{
		public int amount;

		public Health () {
		}

		public Health (int a) {
			amount = a;
		}

		public int getHealth(){
			return amount;
		}

		public void takeHit(int d){
			amount -= d;
		}


	}
}

